# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\RedisClient:
        arguments:
            $redisDsn: '%env(REDIS_DSN)%'

    App\Service\LdapUserProviderInterface:
        alias: App\Service\MockLdapUserProvider
